# Generated by Django 5.0.3 on 2024-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastroUsuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
